In [14]:
import pandas as pd
from textblob import TextBlob
import re
from nltk.stem import WordNetLemmatizer
import csv

In [74]:
df = pd.read_csv('data/TyrionLannister_Tweets.csv')
df.head()

,username,date,retweets,favorites,text,geo,mentions,hashtags,id,permalink
0,NaN,02-05-2019 13:21,1,1,Good call,NaN,NaN,NaN,NaN,NaN
1,NaN,02-05-2019 12:49,0,0,if u die we all lost everyone and everything #...,NaN,NaN,# # # # # # # # #,1.123990e+18,https://twitter.com/ehfo0/status/1123993006586...
2,NaN,02-05-2019 12:18,0,0,# FanArt by trinket_truck! # TyrionLannister #...,NaN,@,# # # # # #,1.123990e+18,https://twitter.com/CharlesBMF/status/11239851...
3,NaN,01-05-2019 11:01,0,3,FREE DELIVERY Order now and get # freedelivery...,NaN,NaN,NaN,NaN,NaN
4,NaN,01-05-2019 00:24,0,0,Hey! Meet Khan from Pakistan Hi Peter! # GOT8 ...,NaN,NaN,# # # # # # # # # # # #,1.123440e+18,https://twitter.com/orabusted/status/112344300...

In [75]:
updated_df = df['text']
updated_df.head()

0                                            Good call
1    if u die we all lost everyone and everything #...
2    # FanArt by trinket_truck! # TyrionLannister #...
3    FREE DELIVERY Order now and get # freedelivery...
4    Hey! Meet Khan from Pakistan Hi Peter! # GOT8 ...
Name: text, dtype: object

In [76]:
tweet_text = []
tweet_timestamp = []
tweet_date = []
tweet_char = []
tweet_sen = []
tweet_pol = []
tweet_sub = []



for key, tweet in updated_df.items():
        analysis = TextBlob(tweet)

        senti = ""
        polarity = 0.0
        subjectivity = 0.0
    
        if analysis.sentiment[0]>0:
           senti = "Pos"
        elif analysis.sentiment[0]<0:
           senti = "Neg"
        else:
           senti = "Neu"
        polarity = float(analysis.sentiment[0])
        subjectivity = float(analysis.sentiment[1])

        tweet_text.append(tweet)
        tweet_pol.append(polarity)
        tweet_sen.append(senti)
        tweet_sub.append(subjectivity)
#         print(tweet_text)

In [77]:
df = pd.DataFrame({
  "text": tweet_text,
  "sentiment" : tweet_sen,
  "polarity" : tweet_pol,
  "subjectivity" : tweet_sub,
})

df.head()

,text,sentiment,polarity,subjectivity
0,Good call,Pos,0.70,0.60
1,if u die we all lost everyone and everything #...,Neu,0.00,0.00
2,# FanArt by trinket_truck! # TyrionLannister #...,Neu,0.00,0.00
3,FREE DELIVERY Order now and get # freedelivery...,Pos,0.45,0.65
4,Hey! Meet Khan from Pakistan Hi Peter! # GOT8 ...,Neu,0.00,0.00

In [71]:
df.to_csv("data/TyrionLannister_Sentiments.csv", index=False)

In [72]:
df = df.dropna()
stemmer = WordNetLemmatizer()

for index, row in df.iterrows():
    # Remove all the special characters
    test_preproc = re.sub(r'\W', ' ', str(row["text"]))

    # remove all single characters
    test_preproc = re.sub(r'\s+[a-zA-Z]\s+', ' ', test_preproc)

    # Remove single characters from the start
    test_preproc = re.sub(r'\^[a-zA-Z]\s+', ' ', test_preproc) 

    # Substituting multiple spaces with single space
    test_preproc = re.sub(r'\s+', ' ', test_preproc, flags=re.I)

    # Removing prefixed 'b'
    test_preproc = re.sub(r'^b\s+', '', test_preproc)

    # Converting to Lowercase
    test_preproc = test_preproc.lower()
    
    # Lemmatization
    test_preproc = test_preproc.split()

    test_preproc = [stemmer.lemmatize(word) for word in test_preproc]
    comb_string = ' '.join(test_preproc)
    df.loc[index, "Preprocess"] = comb_string

In [73]:
df.to_csv("data/SansaStark_Sentiments.csv", index=False)